# Instrukcja.
#
# 1. Zmienne środowiskowe 'environment' 
#     prezentowane są w postaci tablicy, jeśli chcemy zmienić albo dodać jakąś wartość wystarczy ją zmodyfikować/dopisać
#
# Przykład
#
# services:
#   mysqldb:
#     environment:
#       SERVICE_TAGS: 'dev'
#
#
# 2. Porty 
#     prezentowane są w następujący sposób: "A:B", gdzie A to port, przez który możemy wejść (np. w przeglądarce) (tz zwenętrzy) na port B w kontenerze (wewnętrzny).
#
# Przykład
# Jeśli chcemy mieć dostęp do MySQL na zewnątrz na porcie 3307, modyfikujemy konfigurację w ten sposób:
#
# services:
#   mysqldb:
#     ports:
#       - "3307:3306"

version: '3.9'

services:
  mysqldb:
    environment:
      SERVICE_TAGS: 'dev'

  nodeapp:
    environment:
      SERVICE_TAGS: 'dev'