version: "3.9"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql-container
    command: --authentication_policy=mysql_native_password
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./docker/data/database:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASS}
      SERVICE_TAGS: ${APP_TAG}
      SERVICE_NAME: mysqldb
    networks:
      - akai-todo-network

  nodeapp:
    build: .
    container_name: nodeapp-container
    image: nodeapp:v1
    volumes:
      - ./:/usr/code
    ports:
      - ${NODE_PORT}:3000
    expose:
      - 3000
    environment:
      PORT: 3000
      DB_HOST: mysqldb # point to mysql db docker service
      DB_PORT: 3306 # point to internal container port
      DB_DIALECT: mysql
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SERVICE_TAGS: ${APP_TAG}
      SERVICE_NAME: nodeapp
    depends_on:
      - mysqldb
    networks:
      - akai-todo-network

networks:
  akai-todo-network:
    driver: bridge
